language: node_js
cache: yarn
node_js:
  - "6"
install:
  - npm install
  - npm run build
git:
   depth: false
before_deploy:
  - cd dist
deploy:
  skip_cleanup: true
  provider: azure_web_apps
  username: $AZURE_FTP_USER
  password: $AZURE_FTP_PASSWORD
  site: project-ivy
  verbose: true
  on:
    tags: true