export const BEER_CHANGE = 'BEER_CHANGE';

export const BRAND_CHANGE = 'BRAND_CHANGE';

export const CONSUMATION_CHANGE = 'CONSUMATION_CHANGE';

export const ADD_BEER_SUCCESS = 'ADD_BEER_SUCCESS';

export const ADD_BRAND_SUCCESS = 'ADD_BRAND_SUCCESS';

export const ADD_CONSUMATION_SUCCESS = 'ADD_CONSUMATION_SUCCESS';

export const GET_CONSUMATION_BEERS_SUCCESS = 'GET_CONSUMATION_BEERS_SUCCESS';

export const GET_BRANDS_SUCCESS = 'GET_BRANDS_SUCCESS';

export const GET_CONSUMATIONS_SUCCESS = 'GET_CONSUMATIONS_SUCCESS';

export const GET_CONSUMATION_SUM_SUCCESS = 'GET_CONSUMATION_SUM_SUCCESS';

export const GET_CONSUMATION_SUM_BY_BEER_SUCCESS = 'GET_CONSUMATION_SUM_BY_BEER_SUCCESS';

export const GET_SERVINGS_SUCCESS = 'GET_SERVINGS_SUCCESS';