export const GET_POI_CATEGORIES = 'GET_POI_CATEGORIES';
export const GET_POI_CATEGORIES_SUCCESS = 'GET_POI_CATEGORIES_SUCCESS';

export const GET_VENDORS = 'GET_VENDORS';
export const GET_VENDORS_SUCCESS = 'GET_VENDORS_SUCCESS';

export const GET_EXPENSE_FILE_TYPES = 'GET_EXPENSE_FILE_TYPES';
export const GET_EXPENSE_FILE_TYPES_SUCCESS = 'GET_EXPENSE_FILE_TYPES_SUCCESS';