"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GET_POI_CATEGORIES = 'GET_POI_CATEGORIES';
exports.GET_POI_CATEGORIES_SUCCESS = 'GET_POI_CATEGORIES_SUCCESS';
exports.GET_VENDORS = 'GET_VENDORS';
exports.GET_VENDORS_SUCCESS = 'GET_VENDORS_SUCCESS';
exports.GET_EXPENSE_FILE_TYPES = 'GET_EXPENSE_FILE_TYPES';
exports.GET_EXPENSE_FILE_TYPES_SUCCESS = 'GET_EXPENSE_FILE_TYPES_SUCCESS';
