export const GET_EXPENSE_SUM_BY_MONTH_SUCCESS = 'GET_EXPENSE_SUM_BY_MONTH_SUCCESS';

export const GET_ONLINE_DATA_SUCCESS = 'GET_ONLINE_DATA_SUCCESS';

export const GET_CONSUMATIONS_SUCCESS = 'GET_CONSUMATIONS_SUCCESS';

export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';

export const GET_RECENT_EXPENSES_SUCCESS = 'GET_RECENT_EXPENSES_SUCCESS';

export const GET_LAST_LOCATION_SUCCESS = 'GET_LAST_LOCATION_SUCCESS';

export const GET_CAR_LOG_LATEST_SUCCESS = 'GET_CAR_LOG_LATEST_SUCCESS';

export const GET_EXPENSE_SUM_TODAY_SUCCESS = 'GET_EXPENSE_SUM_TODAY_SUCCESS';

export const GET_EXPENSE_SUM_THIS_WEEK_SUCCESS = 'GET_EXPENSE_SUM_THIS_WEEK_SUCCESS';

export const GET_EXPENSE_SUM_THIS_MONTH_SUCCESS = 'GET_EXPENSE_SUM_THIS_MONTH_SUCCESS';