export const GET_EXPENSE_SUM_BY_MONTH_SUCCESS = 'GET_EXPENSE_SUM_BY_MONTH_SUCCESS';

export const GET_ONLINE_DATA_SUCCESS = 'GET_ONLINE_DATA_SUCCESS';

export const GET_CONSUMATIONS_SUCCESS = 'GET_CONSUMATIONS_SUCCESS';

export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';