export const ADD_EXPENSE = 'ADD_EXPENSE';
export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSE_SUCCESS';
export const ADD_EXPENSE_ANOTHER_SUCCESS = 'ADD_EXPENSE_ANOTHER_SUCCESS';

export const CLOSE_MODAL = 'CLOSE_MODAL';

export const EDIT_EXPENSE = 'EDIT_EXPENSE';

export const GET_CARDS = 'GET_CARDS';
export const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS';
export const GET_CURRENCIES = 'GET_CURRENCIES';
export const GET_CURRENCIES_SUCCESS = 'GET_CURRENCIES_SUCCESS';
export const GET_EXPENSES = 'GET_EXPENSES';
export const GET_EXPENSES_SUCCESS = 'GET_EXPENSES_SUCCESS';
export const GET_VENDORS = 'GET_VENDORS';
export const GET_VENDORS_SUCCESS = 'GET_VENDORS_SUCCESS';
export const GET_PAYMENT_TYPES = 'GET_PAYMENT_TYPES';
export const GET_PAYMENT_TYPES_SUCCESS = 'GET_PAYMENT_TYPES_SUCCESS';
export const GET_VENDOR_POIS_SUCCESS = 'GET_VENDOR_POIS_SUCCESS';
export const GET_EXPENSE_TYPES = 'GET_EXPENSE_TYPES';
export const GET_EXPENSE_TYPES_SUCCESS = 'GET_EXPENSE_TYPES_SUCCESS';
export const GET_SUM = 'GET_SUM';
export const GET_SUM_SUCCESS = 'GET_SUM_SUCCESS';

export const CHANGED_EXPENSE = 'CHANGED_EXPENSE';
export const CHANGED_FILTERS = 'CHANGED_FILTERS';

export const NEW_EXPENSE = 'NEW_EXPENSE';

export const OPEN_MODAL = 'OPEN_MODAL';

export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
export const UPDATE_EXPENSE_SUCCESS = 'UPDATE_EXPENSE_SUCCESS';