export const GET_FLIGHT_COUNT_BY_AIRPORT_SUCCESS = 'GET_FLIGHT_COUNT_BY_AIRPORT_SUCCESS';

export const GET_FLIGHTS_SUCCESS = 'GET_FLIGHTS_SUCCESS';

export const FLIGHTS_FILTERS_CHANGED = 'FLIGHTS_FILTERS_CHANGED';