export const CHANGED_FILTERS = 'CHANGED_FILTERS';

export const CLOSE_MODAL = 'CLOSE_MODAL';

export const GET_COUNTRIES_VISITED_BOUNDARIES = 'GET_COUNTRIES_VISITED_BOUNDARIES';
export const GET_COUNTRIES_VISITED_BOUNDARIES_SUCCESS = 'GET_COUNTRIES_VISITED_BOUNDARIES_SUCCESS';

export const GET_TRIPS = 'GET_TRIPS';
export const GET_TRIPS_SUCCESS = 'GET_TRIPS_SUCCESS';

export const OPEN_MODAL = 'OPEN_MODAL';