import React from 'react';
import { BiDrink, BiRestaurant, BiTaxi, BiDollar, BiCameraMovie, BiSolidTShirt, BiWrench, BiBook } from 'react-icons/bi';
import { BsMotherboard, BsRouter, BsHeadphones, BsSuitcase, BsSmartwatch, BsHouseDoor, BsPrinter } from 'react-icons/bs';
import { CgGames } from 'react-icons/cg';
import { FaHamburger, FaMemory, FaCouch, FaParking, FaTv, FaShoppingBasket, FaCoffee, FaGasPump, FaWarehouse, FaUsb, FaCar, FaGlasses, FaMobile, FaRoad, FaBolt, FaFire, FaBuilding, FaTooth, FaPlane, FaBus, FaSubway, FaHotel, FaDumbbell, FaGamepad, FaCamera, FaBox, FaWater, FaServer, FaLaptop, FaHdd, FaCreditCard, FaBed, FaWifi, FaVolumeUp, FaStethoscope, FaUtensils, FaMoneyBill, FaBiking } from 'react-icons/fa';
import { FiCpu, FiPower, FiMonitor, FiTool } from 'react-icons/fi';
import { FcInspection } from 'react-icons/fc';
import { FaFerry } from 'react-icons/fa6';
import { GiPresent, GiClothes, GiCarWheel, GiFoodTruck, GiSonicShoes, GiHomeGarage, GiDeliveryDrone, GiVacuumCleaner, GiCampingTent, GiPerfumeBottle, GiMiner, GiCircularSaw } from 'react-icons/gi';
import { MdBatteryFull, MdFlight, MdCarRepair, MdLocalLaundryService, MdSpa, MdCasino, MdLocalPharmacy, MdPets, MdBeachAccess } from 'react-icons/md';
import { GoPackage } from 'react-icons/go';
import { IoMdTrain } from 'react-icons/io';
import { PiBeerBottleFill, PiSwimmingPool } from 'react-icons/pi';
import { TbMassage, TbSofa, TbMicrophone } from 'react-icons/tb';
import { RiScissorsFill } from 'react-icons/ri';

const icons = {
    ['acommodation']: <FaHotel />,
    ['activities']: <FaGamepad />,
    ['administration-fees']: <FaMoneyBill />,
    ['alcoholic-beverages']: <BiDrink />,
    ['amusement-park']: <FaGamepad />,
    ['apartment-rent']: <FaBuilding />,
    ['atm-fee']: <FaCreditCard />,
    ['attraction']: <FaGamepad />,
    ['audio-mixer']: <GiMiner />,
    ['bank-account']: <FaCreditCard />,
    ['batteries']: <MdBatteryFull />,
    ['beach-gear']: <MdBeachAccess />,
    ['bedding']: <FaBed />,
    ['betting']: <MdCasino />,
    ['bike']: <FaBiking />,
    ['bike-equipment']: <FaBiking />,
    ['bike-rental']: <FaBiking />,
    ['boat-mooring']: <FaFerry />,
    ['boat-rental']: <FaFerry />,
    ['books']: <BiBook />,
    ['brewing']: <PiBeerBottleFill />,
    ['building']: <FaBuilding />,
    ['bus']: <FaBus />,
    ['cable-car']: <FaSubway />,
    ['cables']: <FaUsb />,
    ['camera']: <FaCamera />,
    ['camping']: <GiCampingTent />,
    ['car']: <FaCar />,
    ['car-accessories']: <GiCarWheel />,
    ['car-inspection']: <FcInspection />,
    ['car-insurance']: <FaCar />,
    ['car-maintenance']: <GiCarWheel />,
    ['car-parts']: <GiCarWheel />,
    ['car-registration']: <FaCar />,
    ['car-rental']: <FaCar />,
    ['car-repair']: <MdCarRepair />,
    ['car-tyre-change']: <GiCarWheel />,
    ['car-tyres']: <GiCarWheel />,
    ['charger']: <FaBolt />,
    ['cigarettes']: <FaFire />,
    ['cinema']: <BiCameraMovie />,
    ['circular-saw']: <GiCircularSaw />,
    ['cloakroom']: <GiClothes />,
    ['clothes']: <GiClothes />,
    ['clothes-other']: <GiClothes />,
    ['coffee']: <FaCoffee />,
    ['computers']: <FaLaptop />,
    ['concert']: <FaVolumeUp />,
    ['contact-lenses']: <FaGlasses />,
    ['credit-card-membership']: <FaCreditCard />,
    ['currency-conversion']: <FaMoneyBill />,
    ['data-storage']: <FaHdd />,
    ['delivery']: <GoPackage />,
    ['dentist']: <FaTooth />,
    ['developer-subscription']: <FaLaptop />,
    ['development-boards']: <FiCpu />,
    ['documents']: <FaBox />,
    ['domain']: <FaServer />,
    ['donation']: <BiBook />,
    ['drill']: <BiWrench />,
    ['drinks']: <BiDrink />,
    ['drive-caddy']: <FaHdd />,
    ['drivers-license']: <FaCar />,
    ['drone']: <GiDeliveryDrone />,
    ['dry-cleaning']: <MdLocalLaundryService />,
    ['e-mail-subscription']: <FaServer />,
    ['education']: <BiBook />,
    ['electric-tools']: <FiTool />,
    ['electricity']: <FaBolt />,
    ['electronics']: <FaBolt />,
    ['entertainment']: <FaGamepad />,
    ['fast-food']: <FaHamburger />,
    ['ferry']: <FaFerry />,
    ['finances']: <FaMoneyBill />,
    ['fines']: <FaMoneyBill />,
    ['flash-memory']: <FaHdd />,
    ['flight']: <MdFlight />,
    ['flight-services']: <FaPlane />,
    ['flooring']: <FaWarehouse />,
    ['food']: <FaUtensils />,
    ['food-delivery']: <GiFoodTruck />,
    ['food-outside']: <FaUtensils />,
    ['fuel']: <FaGasPump />,
    ['furniture']: <FaCouch />,
    ['games']: <CgGames />,
    ['garage']: <GiHomeGarage />,
    ['gas']: <FaFire />,
    ['gas-bottle']: <FaFire />,
    ['glasses']: <FaGlasses />,
    ['groceries']: <FaShoppingBasket />,
    ['guided-tour']: <FaBuilding />,
    ['gym']: <FaDumbbell />,
    ['hair-clipper']: <RiScissorsFill />,
    ['hairdresser']: <RiScissorsFill />,
    ['hard-disk']: <FaHdd />,
    ['headphones']: <BsHeadphones />,
    ['health']: <FaStethoscope />,
    ['health-services']: <FaStethoscope />,
    ['heater']: <FaFire />,
    ['hostel']: <FaBed />,
    ['hosting']: <FaServer />,
    ['hotel']: <FaHotel />,
    ['house-rent']: <FaBuilding />,
    ['house-repair']: <FaWarehouse />,
    ['house-supplies']: <FaWarehouse />,
    ['housing']: <FaBuilding />,
    ['ice-skating']: <PiSwimmingPool />,
    ['internet-banking']: <FaCreditCard />,
    ['internet-services']: <FaWifi />,
    ['isp']: <FaWifi />,
    ['jacket']: <GiClothes />,
    ['jigsaw']: <BiWrench />,
    ['karting']: <FaCar />,
    ['kitchen-supplies']: <FaUtensils />,
    ['language-classes']: <BiBook />,
    ['laptop']: <FaLaptop />,
    ['laptop-accessories']: <FaLaptop />,
    ['laundry']: <MdLocalLaundryService />,
    ['locker-room']: <FaWarehouse />,
    ['lost-money']: <FaMoneyBill />,
    ['lounge']: <TbSofa />,
    ['massage']: <TbMassage />,
    ['medical-insurance']: <FaStethoscope />,
    ['medications']: <MdLocalPharmacy />,
    ['membership']: <FaCreditCard />,
    ['memory-cards']: <FaHdd />,
    ['metro']: <FaSubway />,
    ['microphones']: <TbMicrophone />,
    ['mobile-phone']: <FaMobile />,
    ['mobile-phone-accessories']: <FaMobile />,
    ['mobile-subscription']: <FaMobile />,
    ['monitor']: <FiMonitor />,
    ['motherboard']: <BsMotherboard />,
    ['museum']: <FaBuilding />,
    ['national-park']: <MdPets />,
    ['network-switch']: <BsRouter />,
    ['night-club']: <FaVolumeUp />,
    ['nutrition-supplements']: <MdLocalPharmacy />,
    ['office-supplies']: <FaBox />,
    ['optical-media']: <FaHdd />,
    ['paintball']: <FaGamepad />,
    ['pants']: <GiClothes />,
    ['parking']: <FaParking />,
    ['parking-ticket']: <FaParking />,
    ['passport']: <FaMoneyBill />,
    ['pc']: <FaLaptop />,
    ['pc-case']: <FaLaptop />,
    ['pc-cooler']: <FaLaptop />,
    ['pc-peripherals']: <BsHeadphones />,
    ['pcie-controller']: <FiCpu />,
    ['pedal-boat']: <FaFerry />,
    ['perfume']: <GiPerfumeBottle />,
    ['peripherals']: <BsHeadphones />,
    ['personal']: <FaMoneyBill />,
    ['portable-fridge']: <FaBox />,
    ['postal-services']: <GoPackage />,
    ['power-supply']: <FiPower />,
    ['power-tools']: <BiWrench />,
    ['present']: <GiPresent />,
    ['printer']: <BsPrinter />,
    ['printer-supplies']: <BsPrinter />,
    ['printing']: <BsPrinter />,
    ['processor']: <FiCpu />,
    ['public-transportation']: <FaBus />,
    ['radiotelevision']: <FaTv />,
    ['rafting']: <FaWater />,
    ['ram-memory']: <FaMemory />,
    ['restaurant']: <BiRestaurant />,
    ['routers']: <BsRouter />,
    ['server']: <FaServer />,
    ['sex-toys']: <GiPresent />,
    ['shirt']: <BiSolidTShirt />,
    ['shisha-bar']: <BiDrink />,
    ['shoes']: <GiSonicShoes />,
    ['smart-home']: <BsHouseDoor />,
    ['smart-watch']: <BsSmartwatch />,
    ['software']: <FaLaptop />,
    ['solarium']: <MdSpa />,
    ['souvenir']: <GiPresent />,
    ['subscriptions']: <FaCreditCard />,
    ['suitcase']: <BsSuitcase />,
    ['table-football']: <FaGamepad />,
    ['taxi']: <BiTaxi />,
    ['tent']: <GiCampingTent />,
    ['things']: <FaBox />,
    ['toll']: <FaRoad />,
    ['tools']: <FiTool />,
    ['towel-rent']: <MdSpa />,
    ['toys']: <FaGamepad />,
    ['tracker-tag']: <BsSmartwatch />,
    ['traffic-fine']: <FaCar />,
    ['train']: <IoMdTrain />,
    ['transportation']: <FaBus />,
    ['travel-insurance']: <FaPlane />,
    ['travel-pass']: <FaBus />,
    ['tv']: <FaTv />,
    ['tv-remote']: <FaTv />,
    ['tv-stick']: <FaTv />,
    ['utilities']: <FaBolt />,
    ['utilities-garbage']: <FaBox />,
    ['vacuum-cleaner']: <GiVacuumCleaner />,
    ['visa-application']: <FaMoneyBill />,
    ['vr-game']: <FaGamepad />,
    ['water']: <FaWater />,
    ['wc']: <BsHouseDoor />,
    ['wearables']: <BsSmartwatch />,
    ['weed']: <MdLocalPharmacy />,
    ['wellness-and-sauna']: <MdSpa />,
    ['zoo-park']: <MdPets />,
};

interface Props {
    typeId: string
}

const ExpenseTypeIcon = ({ typeId }: Props) => icons[typeId] ?? <BiDollar />;

export default ExpenseTypeIcon;